[package]
name = "tps6507x"
version = "0.1.0"
authors = ["Roman M. <m3angreen@gmail.com>"]
edition = "2018"

[dependencies]
nb = "1"
embedded-hal = { version = "0.2.2", features = ["unproven"] }
bitfield = "0.13"

[dev-dependencies]
embedded-hal-mock = "0.7"

